controller_list:
  - name: fake_gripper_joints_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_2
      - joint_3
      - joint_7
      - joint_11
      - joint_4
      - joint_8
      - joint_12
initial:  # Define initial robot poses per group
#  - group: gripper_joints
#    pose: home

  []