controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_5
      - joint_13
      - joint_17
      - joint_25
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_6
      - joint_14
      - joint_18
      - joint_26
initial:  # Define initial robot poses per group
#  - group: left_arm
#    pose: home

  []